namespace: "mateothegreat"
name: "aws_ec2_hostname"
version: "0.0.1"
readme: "README.md"
authors:
  - "Matthew Davis (https://matthewdavis.io)"
description: "Update instance hostname based on tag:Name"
license: ["MIT"]
license_file: "COPYING"
tags: ["cloud", "aws", "vpc", "hostname", "ec2"]
repository: "https://github.com/mateothegreat/aws-ec2-hostname.git"
homepage: "https://github.com/mateothegreat/aws-ec2-hostname"
issues: "https://github.com/mateothegreat/aws-ec2-hostname/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
